CREATE TABLE IF NOT EXISTS FEE_SETUP
(
FEE_ID SERIAL NOT NULL,
TENANT_ID NUMBER NOT NULL,
FEE_NAME TEXT NOT NULL,
CONSTRAINT FEE_SETUP_PKEY PRIMARY KEY (FEE_ID),
CONSTRAINT FEE_NAME_UNIQUE UNIQUE (FEE_NAME, TENANT_ID)
)
;
CREATE INDEX FEE_ID_IX_FEEID_TENANTID ON FEE_SETUP(FEE_ID,TENANT_ID)
; 

CREATE TABLE IF NOT EXISTS SUBJECT_SETUP
(
SUBJECT_ID SERIAL NOT NULL,
TENANT_ID NUMBER NOT NULL,
SUBJECT_NAME TEXT NOT NULL,
CONSTRAINT SUBJECT_SETUP_PKEY PRIMARY KEY (SUBJECT_ID),
CONSTRAINT SUNJECT_NAME_UNIQUE UNIQUE (SUBJECT_NAME, TENANT_ID)
)
;
CREATE INDEX SUBJECT_ID_IX_SUBJECTID_TENANTID ON SUBJECT_SETUP(SUBJECT_ID,TENANT_ID)
; 

CREATE TABLE IF NOT EXISTS EXAM_SETUP
(
EXAM_ID SERIAL NOT NULL,
TENANT_ID NUMBER NOT NULL,
EXAM_NAME TEXT NOT NULL,
FREQUENCY TEXT NOT NULL,
MARKS NUMBER NOT NULL,
EXTRENAL BOOLEAN NOT NULL,
CONSTRAINT EXAM_SETUP_PKEY PRIMARY KEY (EXAM_ID),
CONSTRAINT EXAM_NAME_UNIQUE UNIQUE (EXAM_NAME, TENANT_ID)
)
;

CREATE TABLE IF NOT EXISTS SESSION_TYPE_SETUP
(
SESSION_TYPE_ID SERIAL NOT NULL,
TENANT_ID NUMBER NOT NULL,
SESSION_TYPE_NAME TEXT NOT NULL,
DURATION NUMBER NOT NULL,
CONSTRAINT SESSION_TYPE_SETUP_PKEY PRIMARY KEY (SESSION_TYPE_ID),
CONSTRAINT SESSIONTYPE_NAME_UNIQUE UNIQUE (SESSION_TYPE_NAME, TENANT_ID)
)
;

CREATE TABLE IF NOT EXISTS SESSION_INSTANCE_SETUP
(
SESSION_INSTANCE_ID SERIAL NOT NULL,
TENANT_ID NUMBER NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
CONSTRAINT SESSION_SETUP_PKEY PRIMARY KEY (SESSION_INSTANCE_ID)
)
;

CREATE TABLE IF NOT EXISTS COURSE_SETUP
(
COURSE_ID SERIAL NOT NULL,
TENANT_ID NUMBER NOT NULL,
COURSE_NAME TEXT NOT NULL,
SESSION_TYPE NUMBER NOT NULL,
TOTAL_SESSION NUMBER NOT NULL,
CONSTRAINT COURSE_SETUP_PKEY PRIMARY KEY (COURSE_ID),
CONSTRAINT COURSE_NAME_UNIQUE UNIQUE (COURSE_NAME, TENANT_ID)
)
;


CREATE TABLE IF NOT EXISTS COURSE_FEE_SETUP
(
COURSE_FEE_ID SERIAL NOT NULL,
COURSE_ID NUMBER NOT NULL,
TENANT_ID NUMBER NOT NULL,
FEE_ID TEXT NOT NULL,
AMOUNT NUMBER NOT NULL,
FREQUECNY NUMBER NOT NULL,
CONSTRAINT COURSE_FEE_SETUP_PKEY PRIMARY KEY (COURSE_FEE_ID)
)
;

CREATE TABLE IF NOT EXISTS COURSE_SUBJECT_SETUP
(
COURSE_SUBJECT_ID SERIAL NOT NULL,
COURSE_ID NUMBER NOT NULL,
TENANT_ID NUMBER NOT NULL,
SUBJECT_ID TEXT NOT NULL,
OPTIONAL BOOLEAN NOT NULL,
CONSTRAINT COURSE_SUBJECT_SETUP_PKEY PRIMARY KEY (COURSE_SUBJECT_ID)
)
;

CREATE TABLE IF NOT EXISTS COURSE_BATCH_SETUP
(
COURSE_BATCH_ID SERIAL NOT NULL,
SECTION TEXT,
COURSE_ID NUMBER NOT NULL,
TENANT_ID NUMBER NOT NULL,
SESSION_INSTANCE_ID NUMBER NOT NULL,
SESSION_NUMBER NUMBER NOT NULL,
CONSTRAINT COURSE_BATCH_SETUP_PKEY PRIMARY KEY (COURSE_BATCH_ID)
)
;